# Generated by Django 4.2.5 on 2024-02-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='datesubmiited',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
